-- MySQL Script generated by MySQL Workbench
-- Tue Aug 15 20:01:53 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdfinal
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bdfinal` ;

-- -----------------------------------------------------
-- Schema bdfinal
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdfinal` DEFAULT CHARACTER SET utf8 ;
USE `bdfinal` ;

-- -----------------------------------------------------
-- Table `bdfinal`.`profesor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfinal`.`profesor` ;

CREATE TABLE IF NOT EXISTS `bdfinal`.`profesor` (
  `id_profesor` INT NOT NULL AUTO_INCREMENT,
  `legajo` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_profesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdfinal`.`asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdfinal`.`asignatura` ;

CREATE TABLE IF NOT EXISTS `bdfinal`.`asignatura` (
  `id_asignatura` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `profesor_id_profesor` INT NOT NULL,
  PRIMARY KEY (`id_asignatura`),
  UNIQUE INDEX `id_asignatura_UNIQUE` (`id_asignatura` ASC) VISIBLE,
  INDEX `fk_asignatura_profesor_idx` (`profesor_id_profesor` ASC) VISIBLE,
  CONSTRAINT `fk_asignatura_profesor`
    FOREIGN KEY (`profesor_id_profesor`)
    REFERENCES `bdfinal`.`profesor` (`id_profesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `bdfinal`.`profesor`
-- -----------------------------------------------------
START TRANSACTION;
USE `bdfinal`;
INSERT INTO `bdfinal`.`profesor` (`id_profesor`, `legajo`, `nombre`, `apellido`, `telefono`) VALUES (DEFAULT, 34562, 'Ejempo', 'Numero 1', '000000');
INSERT INTO `bdfinal`.`profesor` (`id_profesor`, `legajo`, `nombre`, `apellido`, `telefono`) VALUES (DEFAULT, 2323, 'Lucas', 'Gabriel', '111111');

COMMIT;

